version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bicis_network


  script_service:
    image: martinamor04/bicis-corunha:latest  
    container_name: get-from-API
    depends_on:
      - mongodb
    networks:
      - bicis_network

networks:
  bicis_network:
    driver: bridge
